name: audit

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '*/30 * * * 1-5'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Setup dependencies
        run: npm ci

      - name: Check npm audit
        id: check_npm_audit
        run: |
          npm audit --parseable | awk -F $'\t' '{printf "[%s] %s - %s %s %s\n", $3,$2, $4,$5,$6}' | uniq  | sed '$d' | perl -pe 's/\n/\\n/g' > audit.txt
          pipestatus=${PIPESTATUS[0]}
          echo "##[set-output name=audit;]$(cat audit.txt)"
          if [ $pipestatus -ne 0 ]; then exit 1; fi

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Notify slack if npm audit return 1
        if: failure()
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
        run: |
          audit=${{ steps.check_npm_audit.outputs.audit }}
          chomped_audit=${audit:0:2800}
          data=$(cat <<EOF
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*podcast-tables npm audit security report*\n$chomped_audit"
                }
              }
            ]
          }
          EOF
          )
          echo $data
          curl -X POST \
               -H 'Content-type: application/json' \
               --data "$data" \
               ${SLACK_INCOMING_WEBHOOK}
