name: ci

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Setup dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: echo not implemented

      - name: Build
        run: npm run build
